# .travis.yml

language: python
sudo: false

env:
  - LUA="luajit=2.0" LUAJIT=luajit-2.0.4
  - LUA="luajit=2.1" LUAJIT=luajit-2.1.0-beta1

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck

script:
  - luacheck --std max+busted *.lua lgsl/*.lua tests/*.lua
  - $LUAJIT test-output.lua
